library(dplyr)
library(ggplot2)

# Project: Frailty_Komoto 2016 primary insurance segment plots
# Author: Nemo Zhou
# Date started: 2026-06-08
# Date last updated: 2026-07-16
#
# ---- Purpose ----
# Create two ordered bar charts from the aggregate participant-count files
# generated by Code/2_EDA/2.1_generate_2016_table1.R. One plot displays primary
# medical (Mx) insurance group/segment counts and the other displays primary
# prescription (Rx) insurance group/segment counts. This script does not
# connect to Redshift or recalculate participant counts.
#

# ---- Input and output files ----
output_dir <- file.path(getwd(), "Outputs")
mx_count_file <- file.path(output_dir, "2.1_mx_segment_counts_2016.csv")
rx_count_file <- file.path(output_dir, "2.1_rx_segment_counts_2016.csv")

required_files <- c(mx_count_file, rx_count_file)
missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0L) {
  stop(
    "Required 2.1 count file(s) not found: ",
    paste(basename(missing_files), collapse = ", "),
    ". Run Code/2_EDA/2.1_generate_2016_table1.R first."
  )
}

# ---- Read the existing aggregate segment counts ----
mx_counts <- read.csv(
  mx_count_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

rx_counts <- read.csv(
  rx_count_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

required_mx_columns <- c(
  "analysis_year",
  "mx_insurance_group",
  "mx_insurance_segment",
  "n_participants"
)
required_rx_columns <- c(
  "analysis_year",
  "rx_insurance_group",
  "rx_insurance_segment",
  "n_participants"
)

if (!all(required_mx_columns %in% names(mx_counts))) {
  stop("The 2.1 Mx segment-count file does not have the expected columns.")
}

if (!all(required_rx_columns %in% names(rx_counts))) {
  stop("The 2.1 Rx segment-count file does not have the expected columns.")
}

# ---- Create ordered group/segment labels ----
mx_counts <- mx_counts |>
  mutate(
    insurance_category = paste(mx_insurance_group, mx_insurance_segment, sep = " - ")
  ) |>
  arrange(desc(n_participants)) |>
  mutate(
    insurance_category = factor(
      insurance_category,
      levels = rev(insurance_category)
    )
  )

rx_counts <- rx_counts |>
  mutate(
    insurance_category = paste(rx_insurance_group, rx_insurance_segment, sep = " - ")
  ) |>
  arrange(desc(n_participants)) |>
  mutate(
    insurance_category = factor(
      insurance_category,
      levels = rev(insurance_category)
    )
  )

# ---- Create ordered participant-count bar charts ----
mx_plot <- ggplot(
  mx_counts,
  aes(x = insurance_category, y = n_participants)
) +
  geom_col(fill = "#2C7FB8", width = 0.7) +
  geom_text(
    aes(label = format(n_participants, big.mark = ",", scientific = FALSE)),
    hjust = -0.1,
    size = 3.5
  ) +
  coord_flip(clip = "off") +
  scale_y_continuous(
    labels = function(x) format(x, big.mark = ",", scientific = FALSE),
    expand = expansion(mult = c(0, 0.18))
  ) +
  labs(
    title = "2016 Participants by Primary Mx Insurance Segment",
    x = "Primary Mx insurance group and segment",
    y = "Number of participants"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid.major.y = element_blank(),
    plot.margin = margin(5.5, 30, 5.5, 5.5)
  )

rx_plot <- ggplot(
  rx_counts,
  aes(x = insurance_category, y = n_participants)
) +
  geom_col(fill = "#41AB5D", width = 0.7) +
  geom_text(
    aes(label = format(n_participants, big.mark = ",", scientific = FALSE)),
    hjust = -0.1,
    size = 3.5
  ) +
  coord_flip(clip = "off") +
  scale_y_continuous(
    labels = function(x) format(x, big.mark = ",", scientific = FALSE),
    expand = expansion(mult = c(0, 0.18))
  ) +
  labs(
    title = "2016 Participants by Primary Rx Insurance Segment",
    x = "Primary Rx insurance group and segment",
    y = "Number of participants"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid.major.y = element_blank(),
    plot.margin = margin(5.5, 30, 5.5, 5.5)
  )

# ---- Save and display the plots ----
ggsave(
  filename = file.path(output_dir, "2.4_primary_mx_segment_participants_2016.png"),
  plot = mx_plot,
  width = 11,
  height = 7,
  dpi = 300
)

ggsave(
  filename = file.path(output_dir, "2.4_primary_rx_segment_participants_2016.png"),
  plot = rx_plot,
  width = 11,
  height = 7,
  dpi = 300
)

print(mx_plot)
print(rx_plot)

message("Primary Mx and Rx insurance segment plots are complete.")
